### ISSUE TITLE
plugin breaks nested query

### ISSUE THREAD

**Issue by darwin2k** [cheezone/mongoose-find-by-reference#2]
I love your plugin- this makes live much easier.

But, I do a nested dateQuery which gives no result when using the mongoose-find-by-reference-plugin

 ```
dateCondition = {
      "timestamps.createdAt": {
        $gte: startIsoDate,
        $lt: endIsoDate,
      },
    };
```
when removing the pluging, the query works.

So maybe check the referenced models at the schema and do the plugins magic only when targeting a referenced model...

**Comment by darwin2k** [comment]
checkout this testcase:
```
"use strict";
const mongoose = require("mongoose");
const { Schema } = mongoose;
const assert = require("assert");
const { MongooseFindByReference } = require("mongoose-find-by-reference");

run().catch(console.error);


async function run() {
  await mongoose.connect("mongodb://user:password@localhost:27017/test", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    timestamps: { createdAt: { type: Date } },
  });

  userSchema.plugin(MongooseFindByReference);

  const User = mongoose.model("User", userSchema);

  await User.create({ timestamps: { createdAt: new Date("2022-07-04T09:18:07.647Z") } });
  const users = await User.find({ "timestamps.createdAt": { $gte: new Date("1994-01-01T00:00:00Z"), $lte: new Date("2222-01-01T00:00:00Z") } });

  assert.equal(users.length, 1);

  console.log("Assertions passed.");
}

```

**Comment by cheezone** [comment]
My plugin will turn your inquiries into:
```js
timestamps: {
    createdAt: {
      '$gte': 1994-01-01T00:00:00.000Z,
      '$lte': 2222-01-01T00:00:00.000Z
    }
  }
```
When I first watched it, there seemed to be no problem, but I solved my doubts with [this URL](https://stackoverflow.com/questions/16002659/how-to-query-nested-objects).

I was trying to solve it.

**Comment by cheezone** [comment]
It has been fixed.

**Comment by darwin2k** [comment]
Thanks! 
This works great.

**Comment by CRAKZOR** [comment]
Hello, I seem to be having this issue, but for a doubly nested query.

`
        let getDeals = Deal.find(
            {
            $and : [
                {
                $or:[
                    { "customer.basicInformation.name": { "$regex": query, "$options": "i" } }
                    ...
`

which looks like the plugin switches it to 

`
{customer: { "basicInformation" {  "$regex": query, "$options": "i" } } }
`
